### ISSUE TITLE
Handling errors in update methods.

### ISSUE THREAD

**Issue by JamesBremner** [SoftwareToolsFactory/SettingsLIB#2]
The specifications for the update methods specify that they throw no exceptions.  They also return void.  So the question is how to handle errors.  Errors are certainly possible, for example if the calling code specifies a reserved SQL word for a group or parameter name.

**Comment by Nuroferatu** [comment]
Hello James,
You are right, did not give this methods second thought.
Throwing exception would help in this case.

**Comment by JamesBremner** [comment]
OK, I will and exception throwing to the update methods in my pull request.

**Comment by JamesBremner** [comment]
I have added a commit to my pull request ( #1 ) which implements throwing an exception when an error occurs in one of the update methods.
